server:
  port: 8100
  tomcat:
    min-spare-threads: 2
proxy:
  #master端所在的地址  api地址
  master:
    host: preview.idofast.com
    port: 443
    tls: true
    getProxyInfoUrl: '/api/master/api/user/detail'   #获取用户信息
    reportStateUrl: '/api/master/api/state/report'   #上报状态
    authPassword: 'idofast'
  v2ray:
    port: 6001
    apiPort: 62789
    host: 127.0.0.1
    tag: 6001
  local:
    #本地主机域名，报告给服务器用的
    host: iplc2.idofast.com

  netty:
    port: 8888

logging:
  file: /var/log/idf/idf-proxy.log
  file.max-history: 7
  level:
    root: info
