server:
  port: 8001

spring:
  datasource:
    username: root
    password: idofast
    url: jdbc:mysql:///test_idf?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.163.com
    username: zmzsstreet@163.com
    password:
    properties.mail.smtp.port: 465 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8
  profiles:
    active: local

email:
  username: zmzsstreet@163.com
  senderName: IdoFast加速器



token:
  secret: nwafu
  # 单位 分钟
  expiration: 43200

#是否真的发送email；方便测试
switch:
  sendEmail: false

alipay:
  signType: RSA2 #签名算法
  protocol: https
  appId: 2016102100734539
  gatewayHost: openapi.alipaydev.com
  merchantPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCR/4/KlECsRcKOdxupRwd4JC0F0nWXlXv7lcjI5x/BQV8htY6q0ItaWDCAVTdMZvcYqTBqtca0j7SxUA6q5THjit1s06nCnFNMzz1GEVJYaHm2lKbAMDEcJ7h2wZaJXwXL0kS0987kKggPg24IRymgNVODVKtdviektN6tjCmBCQ25+d4tvfobnxWJWMijb37OtZxdEPQDplxekOjlsJQnej/3GX26AziBGmnboYHF9lIFCdTdErgAg6S3v2Ll5p7bzqFZJpv7b77urKET+ddYkrLb5337H+Rm9i3NlyX/ySKiVVd6+WdfOIP/4LthDgQgtvbv8WA6pdpAi4W0OchlAgMBAAECggEABSVi5hsPpILY9riQCwlr4/oydBAVAQDN2/JNn3c2EVPCjKefnbm4D7koDH30cwb2ErJz+G7r0BV4ov9VZQSrG4Abieh0BV4JOZ3cZQnbQy57i8n1jrSkJn/n6pesPK9SvvpsXYyWiEhK/HD/gd8wQmtexDRJzgYT06RkbO2R0PB44eHgO8aAn7JcsNYeQC3JNCwlAOzTEgHEkAiu3w7s8igR4+pPwcFBnBQapAFByc7u3zEVcsZaErXBmDTrkrAU3apxUruoBS2HWTkJpnjp7x1Dns16sIRffJ/KW5kXMcW726jv3s+AslwBNm1JXb45ifE60caHu4QRxRVY8NtqQQKBgQDpkFpnSXzO/m+KiZuPfQyW1roikmFdLsF8U7tSBLmtguyfSNm/48QNbEj1ke09UBcH6wQGYblIrriiGkhccfifJweEhXEuoI7PejD8S/vBAOitfw+Jmj3JM9h/WCAdKQQPpv28VjWRxzEDB3DbgsbmuwVrRT5C/BN0roou5x2VXQKBgQCgBdqhfHFxWnjdUW+/p9KvArGJobNbj20frSl+FUuRogCn/yCGo9IweXoL4YrXvH895bgo7b2GQL7JNpCJ7omko1guNOb9/yroDrSCewTpyeZy2RCHxdXqU8chj3VlK1XZa9mKxRV0TpZKZd/UAclMz43/ecnGzDmYpH/lS9oGqQKBgEhZg/eMxxGjtU+X0s0+8kBjYaNF7s0bp6nokhUVC6NY9A1fVrxfRKLX0T3opzGf9pJoVYXYjbmbDeyA8btZPqemQmjloSrNZ4+TjUsKCoE909Wyj1CTq+IAombIGKKPywdCNkU5+zweFOuYSXhl6VEdy87v0xqS1UAGtR1UUFCtAoGAT0o3R5bauxjiFH+aiHOGgDMsdw7JSU/q+SwbCB9TH2kPPC69FhmsN1qpr6Nk4XrD7Y6azqTmKNSB9D92JPIt/4b0VYje//Hkd7F5ncGI8LKa3kNR3oSXdxFl9OoZeDSdyCqZUxpOhB/AdkK+QlVUQhwBtxnIchmVXF3+BUatVGkCgYB5i21A2PWRKjiuq8Pv0yZvOsWI48to+bhVdz2jSGiV7bouGPSpWDJVb++ihFkwuctwCYO3C/Mgcf4/dckjhlyhx0zMWYf9cWaLs2yu5k2GKr08Pypc/oFmVCNGaq9oIfnWxd9m4+fIAdIAlS+Y4n3iCr6+uLE6vnHV4BXxERsZiA==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsOzjwyx8Rck2DyrkdCeYxe5sBGHj3dzTp7XcJxPUhN+Zk7sfBrX8N6oCdLs0avwylnpKTZXbJ6+SxkIQzbJ/XmW9BpFvxiQxtqUqsndvwnHDETLofhUgBvde5ICF7zeWXP+ypTeS+0WYf5cC69cDEJotJUtOJ9Fe8QClKRnkJ+omN+mw2dRQBHrxZThMI/ekHNl6pVxCdjFphsp1aU/WUmfXOyudlhGQ39Vhgc9fYonxXs+dFB++aJudKfNUK3a1gZOoRz780NwU59UbTSuCPh22P/a08wl7LDPRH+uuGO5qMuPxUp23mJtF7FRVLDYQfvBIVr/Sk5H6caPKsNLMYQIDAQAB
  notifyUrl: http://127.0.0.1:8001/pay/callback
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace




