server:
  port: 8001

spring:
  datasource:
    username: root
    password: idofast
    url: jdbc:mysql:///test_idf?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: idofast2020@gmail.com
    password:
    properties.mail.smtp.port: 465 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8


email:
  username: idofast2020@gmail.com
  senderName: IdoFast加速器

swagger:
  production: true

token:
  secret: nwafu
  # 单位 分钟
  expiration: 4320

#是否真的发送email；方便测试
switch:
  sendEmail: false


# 订阅链接用
site:
  host: preview.idofast.com
  enableTls: true


logging:
  file: /var/log/idf/admin.log
  file.max-history: 7
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
#把jpa的参数绑定打印出来


proxy:
  port: 8100
  tls: false
  authPassword: idofast
  wsPath: /idf/
  api:
    rmAccount: /proxy/api/account/del

