server:
  port: 8001
logging:
  level:
    root: info




email:
  #stmp地址
  host: smtp.163.com
  #用户名称
  username: zmzsstreet@163.com
  #密码
  password: LQHKOWYQXYQINDDW
  #收件人显示的名称
  senderName: idofast加速器
  smtpPort: 465
  useSsl: true


  exceedConnections: 你当前的连接数已经超过账号最大限制，当前风险系统自动降低你一半的连接数，并且持续一个小时;如果你在一个小时后，不在触发监控指标，你的账号连接数将恢复。
  vCodeTemplate: '你的验证码为: %s,请在10分钟内使用'
  overdueDate: 你的账号即将于：%s 过期，请留意续费。













spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql:///test_idf?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: zmz121.cn
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
    password: cloudalibaba
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.163.com
    username: zmzsstreet@163.com
    password: LQHKOWYQXYQINDDW
    properties.mail.smtp.port: 465 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: UTF-8





token:
  secret: nwafu
  # 单位 分钟
  expiration: 43200

switch:
  sendEmail: false






---
spring:
  profiles: docker

logging:
  file:
    name: app.log
email:
  #stmp地址
  host: smtp.gmail.com
  #用户名称
  userName: idofast2020@gmail.com
  #密码
  password: zefxjsirguylhgbr
  #端口
  port: 465
  #默认false ,邮件不支持startTls不要开启
  startTlsEnabled: false

  exceedConnections: 你当前的连接数已经超过账号最大限制，当前风险系统自动降低你一半的连接数，并且持续一个小时;如果你在一个小时后，不在触发监控指标，你的账号连接数将恢复。
  vCodeTemplate: '你的验证码为: %s,请在10分钟内使用'
  overdueDate: 你的账号即将于：%s 过期，请留意续费。

